export const DEFAULT_LINES = [
  '@HOME',
  '+bike',
  'The fire burns brightly.',
  'if ride a bike & ?bike',
  "\tThat's cool!",
  '\tgoto @BIKE',
  'if grab the fire',
  '\t+fire',
  '\tOuch!',
  '@BIKE',
  'when fire',
  '\tYou are biking with fire in your hands.',
  'You feel the wind in your hair.',
  'goto @END',
];
